### ISSUE TITLE
 has no attribute 'VMRUN_PATH'

### ISSUE THREAD

**Issue by lluxury** [mechboxes/mech#22]
win7

Traceback (most recent call last):
  File "/usr/bin/mech", line 11, in <module>
    load_entry_point('mech==0.5', 'console_scripts', 'mech')()
  File "/usr/lib/python2.7/site-packages/mech/__main__.py", line 111, in main
    operation(op='start', name=name, options={'gui':gui})
  File "/usr/lib/python2.7/site-packages/mech/__main__.py", line 75, in operation
    method()
  File "/usr/lib/python2.7/site-packages/mech/mech.py", line 63, in start
    vm.start()
  File "/usr/lib/python2.7/site-packages/mech/vmrun.py", line 105, in start
    return self.vmrun( 'start', 'nogui' )
  File "/usr/lib/python2.7/site-packages/mech/vmrun.py", line 46, in vmrun
    output = self.execute( self.VMRUN_PATH, *cmd )
AttributeError: Vmrun instance has no attribute 'VMRUN_PATH'

**Comment by lluxury** [comment]
fixed

new problem is VMWare Tools is not installed, IP address cannot be determined

**Comment by lluxury** [comment]
fixed
failed to vagrant up a cluster

**Comment by ColdHeat** [comment]
I'm not sure if this bug is still an issue, if it is feel free to re-open.
