### ISSUE TITLE
mech cannot import name 'Mech'

### ISSUE THREAD

**Issue by tsouhaieb** [mechboxes/mech#29]
after i installed mech using pip,
when i type 
```
mech --help
```

python error shows, that it cannot import 'Mech'

Sys: osx sierra
error that shows
```
~ ❯❯❯ mech --help                                                                                                                                                     ✘
Traceback (most recent call last):
  File "/usr/local/bin/mech", line 11, in <module>
    load_entry_point('mech==0.6', 'console_scripts', 'mech')()
  File "/usr/local/lib/python3.6/site-packages/mech/__main__.py", line 32, in main
    from mech import Mech
ImportError: cannot import name 'Mech'
```

**Comment by ColdHeat** [comment]
Python 3 compatibility isn't working yet. See https://github.com/mechboxes/mech/pull/26

**Comment by tsouhaieb** [comment]
when i install using pip only (python 2.7),

it shows
```
pip install git+https://github.com/mechboxes/mech.git                                                                                                           ✘
Collecting git+https://github.com/mechboxes/mech.git
  Cloning https://github.com/mechboxes/mech.git to /private/var/folders/6j/_hcdjpvs65v5x01bjpmy28zw0000gn/T/pip-nY6a30-build
Requirement already satisfied: requests in ./Library/Python/2.7/lib/python/site-packages (from mech==0.6)
Collecting clint (from mech==0.6)
  Could not find a version that satisfies the requirement clint (from mech==0.6) (from versions: )
No matching distribution found for clint (from mech==0.6)
```

**Comment by ColdHeat** [comment]
The command you posted works for me.

**Comment by ColdHeat** [comment]
Try just installing from pypi.

**Comment by tsouhaieb** [comment]
thanks, the reason why it was not working, is that i was using the system python (on osx)
