### ISSUE TITLE
Win 7 (64bit)/Python 2.7.15: mech up fails after box was downloaded

### ISSUE THREAD

**Issue by jal2** [mechboxes/mech#43]
This happened on Win7 64 Bit with Python 2.7.15 (x64, installed for all users):
```bash
C:\WINDOWS\system32>c:\Python27\Scripts\mech init bento/ubuntu-16.04
Initializing mech
Loading metadata for box 'bento/ubuntu-16.04'
A `Mechfile` has been initialized and placed in this directory. You
are now ready to `mech up` your first virtual environment!
C:\WINDOWS\system32>c:\Python27\Scripts\mech up
Loading metadata for box 'bento/ubuntu-16.04' (201806.08.0)
Box 'bento/ubuntu-16.04' could not be found. Attempting to download...
URL: https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/201806.08.0/prov
iders/vmware_desktop.box
vmware_desktop.box [################################] 479786/479786 - 00:07:43
Checking box 'bento/ubuntu-16.04' integrity...
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\mech.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\mech\__main__.py", line 39, in main
    return Mech(arguments)()
  File "c:\python27\lib\site-packages\mech\command.py", line 71, in __call__
    obj = klass(arguments)
  File "c:\python27\lib\site-packages\mech\mech.py", line 602, in up
    vmx = utils.init_box(self.box_name, self.box_version, requests_kwargs=reques
ts_kwargs, save=save)
  File "c:\python27\lib\site-packages\mech\utils.py", line 305, in init_box
    name_version_box = add_box(name, name=name, version=version, force=force, sa
ve=save, requests_kwargs=requests_kwargs)
  File "c:\python27\lib\site-packages\mech\utils.py", line 334, in add_box
    return add_mechfile(mechfile, name=name, version=version, force=force, save=
save, requests_kwargs=requests_kwargs)
  File "c:\python27\lib\site-packages\mech\utils.py", line 345, in add_mechfile
    return add_box_url(name, version, url, force=force, save=save, requests_kwar
gs=requests_kwargs)
  File "c:\python27\lib\site-packages\mech\utils.py", line 382, in add_box_url
    return add_box_file(name, version, fp.name, url=url, force=force, save=save)

  File "c:\python27\lib\site-packages\mech\utils.py", line 399, in add_box_file
    tar = tarfile.open(filename, 'r')
  File "c:\python27\lib\tarfile.py", line 1675, in open
    return func(name, "r", fileobj, **kwargs)
  File "c:\python27\lib\tarfile.py", line 1740, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "c:\python27\lib\gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 13] Permission denied: 'c:\\users\\jalbert\\appdata\\local\\temp
\\tmpgsbpdg'

C:\WINDOWS\system32>
```
The directory c:\users\jalbert\appdata\local\temp\ is writable in the cmd.exe:
```bash
C:\WINDOWS\system32>echo Hallo > c:\users\jalbert\appdata\local\temp\huhu
C:\WINDOWS\system32>dir c:\users\jalbert\appdata\local\temp\huhu
 Datenträger in Laufwerk C: ist SYSTEM
 Volumeseriennummer: 50C8-E6F7

 Verzeichnis von c:\users\jalbert\appdata\local\temp

03.07.2018  13:31                 8 huhu
               1 Datei(en),              8 Bytes
               0 Verzeichnis(se), 75.967.459.328 Bytes frei

C:\WINDOWS\system32>
```

**Comment by Kronuz** [comment]
@jal2, it’s not trying to write, it’s trying to read and the permission is denied (from reading); the reason is the tarball was downloaded to a temporary file and such file is still open (from when it was written) but at the same time is being opened again by the tarfile module for extraction, which is not possible under some platforms as temporary files being written have an exclusive lock.
