### ISSUE TITLE
Fail to load mech ssh

### ISSUE THREAD

**Issue by romanharen** [mechboxes/mech#55]
The VM is ready. Connect to it using `mech ssh`

C:\Users\Administrador>mech ssh
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\mech-script.py", line 11, in <module>
    load_entry_point('mech==0.7.6', 'console_scripts', 'mech')()
  File "c:\program files (x86)\python37-32\lib\site-packages\mech\__main__.py", line 39, in main
    return Mech(arguments)()
  File "c:\program files (x86)\python37-32\lib\site-packages\mech\command.py", line 89, in __call__
    obj = klass(arguments)
  File "c:\program files (x86)\python37-32\lib\site-packages\mech\mech.py", line 890, in ssh
    return subprocess.call(cmds)
  File "c:\program files (x86)\python37-32\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\program files (x86)\python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\program files (x86)\python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system can not find the file specified

**Comment by nguyenl95** [comment]
I experience same error. The host and SSH still working though.
